swagger: "2.0"
info:
  title: Beego starter
  description: API docs
  version: 1.0.0
basePath: /v1
schemes:
- http
- https
paths:
  /user/:
    get:
      tags:
      - user
      summary: List of Users
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.User'
definitions:
  models.Post:
    title: Post
    type: object
    properties:
      Created:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      Name:
        type: string
      Updated:
        type: string
        format: datetime
      User:
        $ref: '#/definitions/models.User'
  models.Profile:
    title: Profile
    type: object
    properties:
      Age:
        type: integer
        format: int32
      Created:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      Money:
        type: number
        format: double
      Updated:
        type: string
        format: datetime
      User:
        $ref: '#/definitions/models.User'
  models.User:
    title: User
    type: object
    properties:
      Created:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      Name:
        type: string
      Posts:
        type: array
        items:
          $ref: '#/definitions/models.Post'
      Profile:
        $ref: '#/definitions/models.Profile'
      Updated:
        type: string
        format: datetime
